# Use a smaller Node.js image suitable for production
FROM node:20 as production

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm pkg delete scripts.prepare
RUN npm install --omit=dev

# Copy the rest of the application code to the container
COPY . .

# Expose the default port
EXPOSE 80

# Start the application in production mode
CMD ["npm", "start"]
