name: Lint, Build and Deploy to s3 bucket

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Code
        run: npm run lint
    env:
      GH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      REPO: ${{github.event.repository.name}}
  
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload coverage to Codacy
        run: ./scripts/upload-coverage.sh
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy app to Vercel
        run: ./scripts/deploy-vercel.sh
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
