name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Code
        run: npm run lint
    env:
      GH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      REPO: ${{github.event.repository.name}}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to s3
        run: ./scripts/my-setup.sh
