name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Hello World
        run: echo "Hey guys ${{env.REPO}} - ${{env.GH_TOKEN}}"
      
      - name: Run Shell Script
        run: ./scripts/my-setup.sh
    env:
      GH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      REPO: ${{github.event.repository.name}}
