name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hey guys ${{env.REPO}} - ${{env.GH_TOKEN}}" && npm i && npm test
        shell: bash
    env:
      GH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      REPO: ${{github.event.repository.name}}


  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: goodbye world
        run: echo "Goodbye guys.."
        shell: bash



